[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "python manage.py collectstatic --noinput"
]

[phases.deploy]
cmds = []

[start]
cmd = "gunicorn beneficiary_system.wsgi:application --bind 0.0.0.0:$PORT --workers 2"